site_name: MERFISH3D Analysis

theme:
  name: material 

markdown_extensions:
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Reference:
      - Overview: reference/index.md
      - Classes:
          - DataRegistration: reference/classes/DataRegistration.md
          - PixelDecoder: reference/classes/PixelDecoder.md
          - qi2labDataStore: reference/classes/qi2labDataStore.md
      - Modules:
          - dataio: reference/modules/dataio.md
          - imageprocessing: reference/modules/imageprocessing.md
          - registration: reference/modules/registration.md
          - opmtools: reference/modules/opmtools.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
          setup_commands:
            - import sys; sys.path.insert(0, "src/")