site_name: "merfish3d-analysis"
site_description: "GPU-accelerated 2D/3D MERFISH data processing"
site_author: "Quantitative Imaging and Inference Lab"
site_url: "https://qi2lab.github.io/merfish3d-analysis/"

theme:
  name: material 

markdown_extensions:
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Installation: installation.md
  - DataStore: datastore.md
  - Examples:
    - Synthetic data: examples/statphysbio_synthetic.md
    - Zhuang laboratory mouse brain: examples/zhuang_lab_mouse_brain.md
    - qi2lab human olfactory bulb: examples/qi2lab_human_olfactory_bulb.md
  - Reference:
    - Overview: reference/index.md
    - Classes:
      - DataRegistration: reference/classes/DataRegistration.md
      - PixelDecoder: reference/classes/PixelDecoder.md
      - qi2labDataStore: reference/classes/qi2labDataStore.md
    - Modules:
      - dataio: reference/modules/dataio.md
      - imageprocessing: reference/modules/imageprocessing.md
      - registration: reference/modules/registration.md
      - opmtools: reference/modules/opmtools.md
  - Contributing: contributing.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_private_members: true
          setup_commands:
            - import sys; sys.path.insert(0, "src/")
  - minify:
      minify_html: true

site_dir: site