# https://peps.python.org/pep-0517/
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# https://peps.python.org/pep-0621/
[project]
name = "merfish3d-analysis"
description = "qi2lab 3D MERFISH GPU processing"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "BSD 3-Clause License" }
authors = [
    { email = "douglas.shepherd@asu.edu", name = "Douglas Shepherd" },
]
dynamic = ["version"]
dependencies = ["numpy", "tifffile", "zarr", "numba", "ndstorage",
                "numcodecs", "psfmodels", "cmap", "SimpleITK", 
                "tqdm", "magicgui[pyqt5]", "napari", "pandas",
                "scikit-image", "pyarrow", "tbb", "shapely",
                "imbalanced-learn", "scikit-learn", "clij2-fft", "dask[array]", "rtree",
                "ryomen",
                "ufish @ git+https://github.com/QI2lab/U-FISH.git@main",
                "multiview-stitcher @ git+https://github.com/multiview-stitcher/multiview-stitcher@main",
                "cellpose @ git+https://www.github.com/mouseland/cellpose.git@main",
                "deeds @ git+https://github.com/AlexCoul/deeds-registration@flow_field"]

[tool.hatch.version]
path = "src/wf_merfish/__init__.py"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
only-include = ["src"]
sources = ["src"]

# extras
# https://peps.python.org/pep-0621/#dependencies-optional-dependencies
[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-mock"
]

[project.urls]
Source = "https://github.com/qi2lab/merfish3d-analysis"
Tracker = "https://github.com/qi2lab/merfish3d-analysis/issues"